### ISSUE TITLE
Installation problem facing

### ISSUE THREAD

**Issue by FayZi** [torcellite/imageComparator#3]
Hi,
I've tried to install the package onto my android device but it didn't get installed....Sir what could be the problem i'm not understanding it.
Can you help me on this....Thanks

**Comment by torcellite** [comment]
Please ensure that you've installed the OpenCV Manager, it's a requirement. 

If you still have issues using the application, add more information regarding the device. Make, model, version of Android.

**Comment by FayZi** [comment]
I've installed OpenCV Manager then i tried to install the app but its
giving me this message.

apk installation failed: INSTALL_PARSE_FAILED_NO_CERTIFICATES

What should i do now?

**Comment by torcellite** [comment]
It may be that the APK I've uploaded has signing issues (I'm not able to replicate it because it installs just fine on my Nexus 4), try building the APK yourself.

**Comment by FayZi** [comment]
Thanks for your reply i'll try building this again.

Your apk size is much less.How you achieved this?

how i get reference of opencv packages into my apk file i know the static
way to use opencv library into any project but how we integrate opencv
library into our project?

Is their any opencv.jar file available that will solve the problem.

**Comment by FayZi** [comment]
it works great.

Hello Sir,
How are you?
I'm Undergraduate Computer Science Student and I need some help regarding
the animal face detection algorithm, I really need to know how?
How should I modified the code what backgrounds are required if i
implemented this algorithm in java(android) or c++.

As its my final year project.

Thanks in advance!

**Comment by torcellite** [comment]
This is an issue tracker, FayZi. Please do not post something that isn't related to the issue here.

Locking this thread.
